version: '3.8'
services:
  app:
    container_name: app-go
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - APP_ENV=production
    restart: unless-stopped