services:
  app:
    container_name: app-go
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/root/logs
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - ./mongo_data:/data/db
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data